travis:
  secure:
    BINSTAR_TOKEN: LDxgDGOyGV5NxJNaF4ZESeqJ2SCqT4A+T8wsRDZGT0PX91Lf+Y/zaiuZuzWOvyAwhwYThBiW8HOZPAf2lHx2Sl5VmBBubaEEITtui15FFbdJ3V63C3/QZR369AGMfdeoF3PJUEEFJ3CrDvNQN0PH0EiTE9eUIWC40/UOfyxwyYMbRje6Vl7TbzLmngzIuFt4mGeyvu1TYXJjzwi/VjoUhlfY+9HXz4szFpNKkt59zkIdiVrGliozvvHmY0rXE1vPxjguAXhkcO8V6v8GzCjbr4m1QpPvfR7QD9aCErNHiv+PfoKpIIm/44FHeBwSWyKaydVuj1Nn0hoVt1VOwxg5WXFcUm7oG9Mfks6rtCPMK/JF5gqemfDwRE3ZjFAv5tYP0JY0/+er13q6iwy2/xJg5k9fRkiahbdEccbe8lgjYk0A4LrB0To/dIwKSCRxciAdk29x4BQI9LVeQelwqj5Ur9rWLS2DwP6mUalni48eurOf0X3oRAG9WpVj6yJrTtG4hdos3RNDP8hRUndMRscWAvvdpRgVIbuGVwx3LYzxrVzbbNNZiYZR0Z1BwtALvb/5RdCxsZLnOciTg26fAjFQ1ZpM7WdBo0DZLOrQbHQRKsHuTTGrVzMbk6hq5nXWXPGxgbZORWKx7eNcNDM2LRMA4SpcoOW1d7BxV3L5s6tL904=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
